# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/assetcache/journal_entry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.assetcache import journal_add_entry_pb2 as pogoprotos_dot_data_dot_assetcache_dot_journal__add__entry__pb2
from pogoprotos.data.assetcache import journal_read_entry_pb2 as pogoprotos_dot_data_dot_assetcache_dot_journal__read__entry__pb2
from pogoprotos.data.assetcache import journal_remove_entry_pb2 as pogoprotos_dot_data_dot_assetcache_dot_journal__remove__entry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/assetcache/journal_entry.proto',
  package='pogoprotos.data.assetcache',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.pogoprotos/data/assetcache/journal_entry.proto\x12\x1apogoprotos.data.assetcache\x1a\x32pogoprotos/data/assetcache/journal_add_entry.proto\x1a\x33pogoprotos/data/assetcache/journal_read_entry.proto\x1a\x35pogoprotos/data/assetcache/journal_remove_entry.proto\"\xd6\x01\n\x0cJournalEntry\x12>\n\tadd_entry\x18\x01 \x01(\x0b\x32+.pogoprotos.data.assetcache.JournalAddEntry\x12@\n\nread_entry\x18\x02 \x01(\x0b\x32,.pogoprotos.data.assetcache.JournalReadEntry\x12\x44\n\x0cremove_entry\x18\x03 \x01(\x0b\x32..pogoprotos.data.assetcache.JournalRemoveEntryb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_assetcache_dot_journal__add__entry__pb2.DESCRIPTOR,pogoprotos_dot_data_dot_assetcache_dot_journal__read__entry__pb2.DESCRIPTOR,pogoprotos_dot_data_dot_assetcache_dot_journal__remove__entry__pb2.DESCRIPTOR,])




_JOURNALENTRY = _descriptor.Descriptor(
  name='JournalEntry',
  full_name='pogoprotos.data.assetcache.JournalEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='add_entry', full_name='pogoprotos.data.assetcache.JournalEntry.add_entry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_entry', full_name='pogoprotos.data.assetcache.JournalEntry.read_entry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remove_entry', full_name='pogoprotos.data.assetcache.JournalEntry.remove_entry', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=453,
)

_JOURNALENTRY.fields_by_name['add_entry'].message_type = pogoprotos_dot_data_dot_assetcache_dot_journal__add__entry__pb2._JOURNALADDENTRY
_JOURNALENTRY.fields_by_name['read_entry'].message_type = pogoprotos_dot_data_dot_assetcache_dot_journal__read__entry__pb2._JOURNALREADENTRY
_JOURNALENTRY.fields_by_name['remove_entry'].message_type = pogoprotos_dot_data_dot_assetcache_dot_journal__remove__entry__pb2._JOURNALREMOVEENTRY
DESCRIPTOR.message_types_by_name['JournalEntry'] = _JOURNALENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JournalEntry = _reflection.GeneratedProtocolMessageType('JournalEntry', (_message.Message,), dict(
  DESCRIPTOR = _JOURNALENTRY,
  __module__ = 'pogoprotos.data.assetcache.journal_entry_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.assetcache.JournalEntry)
  ))
_sym_db.RegisterMessage(JournalEntry)


# @@protoc_insertion_point(module_scope)
